### ISSUE TITLE
Please add Docker Compose YAML and .env file.

### ISSUE THREAD

**Issue by colonelmattyman** [ich777/docker-xonotic-server#3]
DockerCompose.yaml
``` yaml
version: '3.8'
services:
  xonotic:
    image: ich777/xonotic:latest
    container_name: Xonotic
    environment:
      - GAME_PARAMS=${GAME_PARAMS}
      - GAME_VERSION=${GAME_VERSION}
      - UID=${UID}
      - GID=${GID}
      - BASIC_URL=${BASIC_URL}
    volumes:
      - ${XONOTIC_VOLUME}:/serverdata/serverfiles
    ports:
      - "3979:3979/tcp"
      - "3979:3979/udp"
    restart: unless-stopped
```

xonotic.env
``` yaml
GAME_PARAMS=
GAME_VERSION=0.8.2
UID=99
GID=100
BASIC_URL=https://dl.xonotic.org/
XONOTIC_VOLUME=/mnt/user/appdata/xonotic
```
